services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: saudapakka_stable_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - saudapakka_postgres_data:/var/lib/postgresql/data # ✅ DB SAFE
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U hello_django -d saudapakka_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./saudapakka_backend
    container_name: saudapakka_backend
    restart: unless-stopped

    volumes:
      - ./saudapakka_backend/src:/app/src
      - ./saudapakka_backend/media:/app/media # ✅ Host media sync
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - SANDBOX_API_KEY=${SANDBOX_API_KEY}
      - SANDBOX_API_SECRET=${SANDBOX_API_SECRET}
      - SANDBOX_BASE_URL=${SANDBOX_BASE_URL}
      - SANDBOX_ENV=${SANDBOX_ENV}
    working_dir: /app

  frontend:
    build: ./saudapakka_frontend
    container_name: saudapakka_frontend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: saudapakka_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./saudapakka_backend/media:/app/media # ✅ Nginx serves images
    depends_on:
      - backend
      - frontend

  certbot:
    image: certbot/certbot
    container_name: saudapakka_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  saudapakka_postgres_data: # ✅ Database safe forever
