version: '3.8'

services:
  backend:
    build:
      context: ./saudapakka_backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=True
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://localhost,http://127.0.0.1
      - CSRF_TRUSTED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://localhost,http://127.0.0.1
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
    volumes:
      - ./saudapakka_backend/src:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./saudapakka_frontend
      target: deps
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./saudapakka_frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    stdin_open: true # Add stdin_open and tty for interactive mode if needed, helps with keeping container alive
    tty: true
